---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: sudo make build
      - store_artifacts:
          path: installed_files.txt
  test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: sudo make install-deps
      - run: make ci
      - store_test_results:
          path: htmlcov/
      - store_test_results:
          path: coverage.xml
      - store_test_results:
          path: test_results/
      - store_artifacts:
          path: test_results/
      - store_artifacts:
          path: htmlcov/
      - store_artifacts:
          path: coverage.xml
      - store_artifacts:
          path: lint_output.txt
  danger:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: bundle install
      - run: make danger

workflows:
  version: 2
  primary:
    jobs:
      - build
      - test:
          requires:
            - build
      - danger:
          requires:
            - test
