---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: make build
  test:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: make ci || make report
      - store_test_results:
        - path: htmlcov/
      - store_artifacts:
        - path: htmlcov/
      - store_artifacts:
        - path: lint_output.txt
      - store_artifacts:
        - path: installed_files.txt
  danger:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: make install-gems
      - run: make danger

workflows:
  version: 2
  primary:
    jobs:
      - build
      - test:
          requires:
            - build
      - danger:
          requires:
            - test
